# Site Settings
title: Sijie Ruan's Homepage
url: 'http://sjruan.me'
baseurl: '' #change it according to your repository name
#about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Sijie Ruan
tagline: Spatio-temporal Data Miner
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Sijie Ruan is a Ph.D. Candidate at the Computer Science and Technology School of Xidian University. 
He received his B.E. degree of Computer Science from Xidian University in 2017. 
His research interests include urban computing, spatio-temporal data management and mining, and distributed computing. 
He is now an algorithm engineer at Urban Computing Lab, JD Finance.'

#sidebar links
email: sjruan94 AT gmail DOT com
scholar: oecbn38AAAAJ
linkedin: sijie-ruan-184102105
github: sjruan
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-118804413-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
