# Site Settings
title: Sijie Ruan's Homepage
url: 'http://sjruan.me'
baseurl: '' #change it according to your repository name
#about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Sijie Ruan
# tagline: Spatio-temporal Data Miner
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '<b>Sijie Ruan</b> is a year-three Ph.D. student in School of Computer Science and Technology of Xidian University. 
His research interests include urban computing, trajectory data mininig, and distributed computing. 
He starts his internship in 2018 as an algorithm engineer at Urban Computing Lab, JD Group, 
supervised by Chief Data Scientist Prof. <a href="http://urban-computing.com/yuzheng" target="_blank">Yu Zheng</a>, and Dr. <a href="http://jie-bao.org/" target="_blank">Jie Bao</a>.'

#sidebar links
email: sjruan94 AT gmail DOT com
scholar: oecbn38AAAAJ
linkedin: sijie-ruan-184102105
github: sjruan
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-118804413-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
